[phases.setup]
aptDeps = ["python3", "python3-pip", "python3-venv"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "source /opt/venv/bin/activate",
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && streamlit run Home.py"

[env]
PATH = "/opt/venv/bin:${PATH}"